name: Validate Homey App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: npm
      - run: npm ci
      - run: npm install --global --no-optional homey
      - run: npm run build
      - run: homey app validate
